controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

addCustomer:
        path: /customer/add
        controller: App\Controller\CustomerRegistrationController::saveData
    # methods: GET|POST

